package org.trishanku.oa.admin.notification.entity;

public enum NotificationEvent {

    SUPER_ADMIN_CREATION,SUPER_ADMIN_MODIFICATION,SUPER_ADMIN_DELETION,SUPER_ADMIN_APPROVAL,
    BANK_ADMIN_CREATION,BANK_ADMIN_MODIFICATION,BANK_ADMIN_DELETION,BANK_ADMIN_APPROVAL,
    BANK_USER_CREATION,BANK_USER_MODIFICATION,BANK_USER_DELETION,BANK_USER_APPROVAL,
    CUSTOMER_ADMIN_CREATION,CUSTOMER_ADMIN_MODIFICATION,CUSTOMER_ADMIN_DELETION,CUSTOMER_ADMIN_APPROVAL,
    CUSTOMER_USER_CREATION,CUSTOMER_USER_MODIFICATION,CUSTOMER_USER_DELETION,CUSTOMER_USER_APPROVAL,
    CUSTOMER_CREATION,CUSTOMER_MODIFICATION,CUSTOMER_DELETION,CUSTOMER_APPROVAL
}
