package org.trishanku.oa.admin.notification.entity;

public enum NotificationEvent {

    SUPER_ADMIN_CREATION,SUPER_ADMIN_MODIFICATION,SUPER_ADMIN_APPROVAL,SUPER_ADMIN_DELETION,BANK_ADMIN_CREATION,BANK_ADMIN_MODIFICATION,BANK_ADMIN_DELETION,BANK_ADMIN_APPROVAL
}
