select * from public.resource_table;

INSERT INTO public.customer_table (system_id, address_line1, address_line2, address_line3, country, customer_id, director_details, director_name, email_address, name, po_box, sponsor_details, sponsor_name, status, tax_registration_number, vat_registration_number, created_date, created_user, modified_date, modified_user, transaction_status, authorisation_date, authorised_user) VALUES ('793a2fa1-6a9f-44c2-88bd-dcf90a9089d4', 'addressline1', 'addressline2', 'addressline3', 'india', 'ravikanth', 'ramakrishna puram, vijayawada', 'mamillapalli', 'ravikanthm@gmail.com', 'Ravikanth Electronics', '11111', 'Kallepallivari street, Vijayawada', 'Venkateswarlu', 'Active', 'Tax12345', 'Vat23456', null, null, null, null, null, null, null);
INSERT INTO public.customer_table (system_id, address_line1, address_line2, address_line3, country, customer_id, director_details, director_name, email_address, name, po_box, sponsor_details, sponsor_name, status, tax_registration_number, vat_registration_number, created_date, created_user, modified_date, modified_user, transaction_status, authorisation_date, authorised_user) VALUES ('a855476b-3836-433d-81cb-35ec255db192', 'addressline21', 'addressline22', 'addressline23', 'india', 'ravikanth2', 'ramakrishna puram, vijayawada2', 'mamillapalli2', 'ravikanthm2@gmail.com', 'Ravikanth Electronics2', '111112', 'Kallepallivari street, Vijayawada2', 'Venkateswarlu', 'Active', 'Tax123452', 'Vat234562', null, null, null, null, null, null, null);
INSERT INTO public.customer_table (system_id, address_line1, address_line2, address_line3, country, customer_id, director_details, director_name, email_address, name, po_box, sponsor_details, sponsor_name, status, tax_registration_number, vat_registration_number, created_date, created_user, modified_date, modified_user, transaction_status, authorisation_date, authorised_user) VALUES ('ea3b9532-5f64-4f89-aa24-e198b93ec6de', 'addressline31', 'addressline32', 'addressline33', 'india', null, 'ramakrishna puram, vijayawada3', 'mamillapalli3', 'ravikanthm3@gmail.com', 'Ravikanth Electronics3', '111113', 'Kallepallivari street, Vijayawada3', 'Venkateswarlu', 'Active', 'Tax123453', 'Vat234563', null, null, null, null, null, null, null);
INSERT INTO public.customer_table (system_id, address_line1, address_line2, address_line3, country, customer_id, director_details, director_name, email_address, name, po_box, sponsor_details, sponsor_name, status, tax_registration_number, vat_registration_number, created_date, created_user, modified_date, modified_user, transaction_status, authorisation_date, authorised_user) VALUES ('8e40ab59-8c91-431f-a695-6c3150eb65ed', 'addressline311', 'addressline32', 'addressline33', 'india', 'Ravikanth3', 'ramakrishna puram, vijayawada3', 'mamillapalli3', 'ravikanthm3@gmail.com', 'Ravikanth Electronics3', '111113', 'Kallepallivari street, Vijayawada3', 'Venkateswarlu', 'Active', 'Tax123453', 'Vat234563', null, null, '2021-09-09 12:41:10.256000', 'ToBeChanged', 1, '2021-09-09 12:53:27.580000', 'ToBeChanged');


INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('a5e1526c-c5e0-44ef-8416-74254f32eb8e', '2021-09-09 13:20:27.000000', 'RAVIKANTH', '2021-09-09 13:20:42.000000', 'RAVIKANTH', '2021-09-09 13:20:52.000000', 'RAVIKANTH', 1, 'SUPER_ADMIN');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('be10ce93-499b-4bff-8f9f-dbe9d2474190', '2021-09-09 13:21:49.000000', 'RAVIKANTH', '2021-09-09 13:21:57.000000', null, null, null, 1, 'BANK_ADMIN');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('3bf804f2-af51-401f-8429-2816c544c414', null, null, null, null, null, null, null, 'CORPORATE_ADMIN');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('0de3a370-40ff-4027-b9f9-cd6f56931d27', null, null, null, null, null, null, null, 'CORPORATE_USER_MAKER');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('02ca5215-7956-41e4-babe-fd99181be0a6', null, null, '2021-09-09 13:22:29.000000', null, null, null, null, 'BANK_USER_MAKER');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('9c369001-99af-48e7-b463-258a9dce2128', null, null, null, null, null, null, null, 'BANK_USER_VIEWER');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('633f051b-4f39-46a7-a5f8-4db4fc0f1438', null, null, null, null, null, null, null, 'BANK_USER_CHECKER');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('bc1e2893-9541-442c-96e0-dd762378c6a1', null, null, null, null, null, null, null, 'CORPORATE_USER_VIEWER');
INSERT INTO public.role_table (uuid, authorisation_date, authorised_user, created_date, created_user, modified_date, modified_user, transaction_status, name) VALUES ('d005a107-1b1f-4ebb-8697-d0dbae66e9da', null, null, null, null, null, null, null, 'CORPORATE_USER_CHECKER');